### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by samsung42** [cowboysdude/MMM-Holiday2#1]
FYI, you should change your instructions from:

~MagicMirror/modules

git clone https://github.com/cowboysdude/MMM-Holidays2
~MagicMirror/modules/MMM-Holidays2

To:

~MagicMirror/modules

git clone https://github.com/cowboysdude/MMM-Holiday2
~MagicMirror/modules/MMM-Holiday2

I was racking my brain to why this would not work and finally figured out the directory name did not reflect what was in the config, and then it started working (I renamed MMM-Holidays2 to MMM-Holiday2).  Also your missing a , for the example config at the end of the days line which causes an error in startup of MM then.

Now that I have it displaying, it has some black box that is not transparent towards the bottom of it.   So the upper 75% of the upcoming events display and are transparent over my background image but the lower 25% of the upcoming events box is black.. Trying to work through that now.

Actually I figured that out also, I changed in the CSS file:
background-image: linear-gradient( rgba(0, 0, 0, 0) 100%, rgba(0, 0, 0, 1) 95% );

And now the whole calendar is transparent and looks nice over background images.

Thanks for the cool module!  I like it allot.

**Comment by cowboysdude** [comment]
Sorry it's taken so long to get back to you!!!!!!!

Thank you so much!
