### ISSUE TITLE
Option to remove date?

### ISSUE THREAD

**Issue by htilly** [cowboysdude/MMM-Holiday2#4]
Any way to disable the prefix dates ?
I.e. just having the Holiday + number of days before event ?

BR
Tilly

**Comment by cowboysdude** [comment]
Look inside the main js file and replace the following with this:

`var HolidayColumn = document.createElement("td");   	
	     if (this.holidays.length > 0) {
          if (DateDiff.inDays(d1, d2) > -1 && DateDiff.inDays(d1, d2) <= this.config.days) {
		   if (todayDate === allDate){
		HolidayColumn.classList.add("bright", "xsmall", "today","row");	
		HolidayColumn.innerHTML = "<font color=#ece96a>&nbsp;&nbsp;" + holiday.summary + " Today</font>";	
		} else {
		HolidayColumn.classList.add("bright", "xsmall", "holiday","row");	
			if (DateDiff.inDays(d1,d2) == "1"){
        HolidayColumn.innerHTML = "&nbsp;&nbsp;" + holiday.summary + " tomorrow!";		
			} else {
		HolidayColumn.classList.add("bright", "xsmall", "holiday","row");
        HolidayColumn.innerHTML = "&nbsp;&nbsp;" + holiday.summary + " In <font color=#ffffff>" + DateDiff.inDays(d1, d2) + "</font> days";
        }		
		}
        holidayWrapper.appendChild(HolidayColumn);
        wrapper.appendChild(holidayWrapper);
        }
        } else {
	    var HolidayColumn = document.createElement("div");
        HolidayColumn.classList.add("bright", "xsmall");
		HolidayColumn.innerHTML = "No Upcoming Holidays";	
        wrapper.appendChild(HolidayColumn);
        }
         }`
