### ISSUE TITLE
I cannot install the module !

### ISSUE THREAD

**Issue by toinfigas** [cowboysdude/MMM-Holiday2#6]
Hey man, i did everything exactly like you said on the post, followed every step but when i start the magic mirror it shows me this error "Please create a config file".
Like i said i did everything you said on the post, EVERYTHING and still cannot put it to work.
When i remove the "CONFIG" from the config.js file it starts working (without the holidays2 module ofc).
I Hope you can help me.
![MgicMirror erro](https://user-images.githubusercontent.com/66489461/83922194-d386e000-a777-11ea-8b22-5bd2661dd85d.png)

**Comment by cowboysdude** [comment]
You must have a config error, my guess is missing coma
